# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Agregar_estudiante.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Agregar_estudiante(object):
    def setupUi(self, Agregar_estudiante):
        Agregar_estudiante.setObjectName("Agregar_estudiante")
        Agregar_estudiante.resize(321, 400)
        Agregar_estudiante.setMinimumSize(QtCore.QSize(321, 400))
        Agregar_estudiante.setMaximumSize(QtCore.QSize(321, 400))
        self.gridLayout = QtWidgets.QGridLayout(Agregar_estudiante)
        self.gridLayout.setObjectName("gridLayout")
        self.lay_ver_principal = QtWidgets.QVBoxLayout()
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lbl_agregar_estudiante = QtWidgets.QLabel(Agregar_estudiante)
        self.lbl_agregar_estudiante.setStyleSheet("font: 35pt \"Gill Sans MT Condensed\";")
        self.lbl_agregar_estudiante.setObjectName("lbl_agregar_estudiante")
        self.lay_ver_principal.addWidget(self.lbl_agregar_estudiante, 0, QtCore.Qt.AlignHCenter)
        self.lay_frm_datos = QtWidgets.QFormLayout()
        self.lay_frm_datos.setObjectName("lay_frm_datos")
        self.txt_codigo_estudiante = QtWidgets.QLineEdit(Agregar_estudiante)
        self.txt_codigo_estudiante.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";")
        self.txt_codigo_estudiante.setText("")
        self.txt_codigo_estudiante.setObjectName("txt_codigo_estudiante")
        self.lay_frm_datos.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_codigo_estudiante)
        self.lbl_nombre_estudiante = QtWidgets.QLabel(Agregar_estudiante)
        self.lbl_nombre_estudiante.setStyleSheet("font: 11pt \"Gill Sans MT\";")
        self.lbl_nombre_estudiante.setObjectName("lbl_nombre_estudiante")
        self.lay_frm_datos.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre_estudiante)
        self.txt_nombre_estudiante = QtWidgets.QLineEdit(Agregar_estudiante)
        self.txt_nombre_estudiante.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";")
        self.txt_nombre_estudiante.setObjectName("txt_nombre_estudiante")
        self.lay_frm_datos.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_nombre_estudiante)
        self.lbl_foto_diag = QtWidgets.QLabel(Agregar_estudiante)
        self.lbl_foto_diag.setStyleSheet("font: 11pt \"Gill Sans MT\";")
        self.lbl_foto_diag.setObjectName("lbl_foto_diag")
        self.lay_frm_datos.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_foto_diag)
        self.lbl_foto_agregar = QtWidgets.QLabel(Agregar_estudiante)
        self.lbl_foto_agregar.setMinimumSize(QtCore.QSize(223, 177))
        self.lbl_foto_agregar.setMaximumSize(QtCore.QSize(223, 177))
        self.lbl_foto_agregar.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border: 2px solid rgba(0, 0, 0, 255);\n"
"padding-top: 10px;\n"
"padding-bottom: 10px;\n"
"padding-right: 30px;\n"
"padding-left: 30px;")
        self.lbl_foto_agregar.setText("")
        self.lbl_foto_agregar.setPixmap(QtGui.QPixmap(":/images/mas.png"))
        self.lbl_foto_agregar.setScaledContents(True)
        self.lbl_foto_agregar.setObjectName("lbl_foto_agregar")
        self.lay_frm_datos.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_foto_agregar)
        self.lbl_codigo_id = QtWidgets.QLabel(Agregar_estudiante)
        self.lbl_codigo_id.setStyleSheet("font: 11pt \"Gill Sans MT\";")
        self.lbl_codigo_id.setObjectName("lbl_codigo_id")
        self.lay_frm_datos.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_codigo_id)
        self.lbl_mensaje = QtWidgets.QLabel(Agregar_estudiante)
        self.lbl_mensaje.setStyleSheet("")
        self.lbl_mensaje.setText("")
        self.lbl_mensaje.setObjectName("lbl_mensaje")
        self.lay_frm_datos.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_mensaje)
        self.lbl_mensaje_2 = QtWidgets.QLabel(Agregar_estudiante)
        self.lbl_mensaje_2.setText("")
        self.lbl_mensaje_2.setObjectName("lbl_mensaje_2")
        self.lay_frm_datos.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lbl_mensaje_2)
        self.lay_ver_principal.addLayout(self.lay_frm_datos)
        self.btn_agregar_estudiante = QtWidgets.QPushButton(Agregar_estudiante)
        self.btn_agregar_estudiante.setStyleSheet("QPushButton#btn_agregar_estudiante {\n"
"    background-color: rgba(255,0,0,126);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton#btn_agregar_estudiante:hover {\n"
"    background-color: rgba(255,155,155,226);\n"
"    border-radius:5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton#btn_agregar_estudiante:pressed {\n"
"    background-color: rgba(255,110,100,255);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}")
        self.btn_agregar_estudiante.setObjectName("btn_agregar_estudiante")
        self.lay_ver_principal.addWidget(self.btn_agregar_estudiante)
        self.gridLayout.addLayout(self.lay_ver_principal, 0, 0, 1, 1)

        self.retranslateUi(Agregar_estudiante)
        QtCore.QMetaObject.connectSlotsByName(Agregar_estudiante)

    def retranslateUi(self, Agregar_estudiante):
        _translate = QtCore.QCoreApplication.translate
        Agregar_estudiante.setWindowTitle(_translate("Agregar_estudiante", "Agregar Estudiante"))
        self.lbl_agregar_estudiante.setText(_translate("Agregar_estudiante", "Agregar estudiante"))
        self.txt_codigo_estudiante.setPlaceholderText(_translate("Agregar_estudiante", "Inserte ID/codigo"))
        self.lbl_nombre_estudiante.setText(_translate("Agregar_estudiante", "Nombre: "))
        self.txt_nombre_estudiante.setPlaceholderText(_translate("Agregar_estudiante", "Inserte nombre"))
        self.lbl_foto_diag.setText(_translate("Agregar_estudiante", "Foto:"))
        self.lbl_codigo_id.setText(_translate("Agregar_estudiante", "ID/Codigo: "))
        self.btn_agregar_estudiante.setText(_translate("Agregar_estudiante", "Agregar"))
        
from notas_estudiantes.images import imagenes_rc
