# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Buscar_estudiante.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Buscar_estudiante(object):
    def setupUi(self, Buscar_estudiante):
        Buscar_estudiante.setObjectName("Buscar_estudiante")
        Buscar_estudiante.setEnabled(True)
        Buscar_estudiante.resize(320, 444)
        Buscar_estudiante.setMinimumSize(QtCore.QSize(320, 444))
        Buscar_estudiante.setMaximumSize(QtCore.QSize(320, 444))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Buscar_estudiante.setWindowIcon(icon)
        Buscar_estudiante.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Buscar_estudiante)
        self.gridLayout.setObjectName("gridLayout")
        self.lay_ver_principal = QtWidgets.QVBoxLayout()
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lbl_buscar_estudiante = QtWidgets.QLabel(Buscar_estudiante)
        self.lbl_buscar_estudiante.setStyleSheet("font: 35pt \"Gill Sans MT Condensed\";")
        self.lbl_buscar_estudiante.setObjectName("lbl_buscar_estudiante")
        self.lay_ver_principal.addWidget(self.lbl_buscar_estudiante, 0, QtCore.Qt.AlignHCenter)
        self.lay_frm_datos = QtWidgets.QFormLayout()
        self.lay_frm_datos.setHorizontalSpacing(50)
        self.lay_frm_datos.setObjectName("lay_frm_datos")
        self.lbl_codigo = QtWidgets.QLabel(Buscar_estudiante)
        self.lbl_codigo.setStyleSheet("font: 11pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_codigo.setObjectName("lbl_codigo")
        self.lay_frm_datos.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_codigo)
        self.txt_codigo = QtWidgets.QLineEdit(Buscar_estudiante)
        self.txt_codigo.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom: 5px;")
        self.txt_codigo.setObjectName("txt_codigo")
        self.lay_frm_datos.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_codigo)
        self.btn_buscar_estudiante = QtWidgets.QPushButton(Buscar_estudiante)
        self.btn_buscar_estudiante.setStyleSheet("QPushButton#btn_buscar_estudiante {\n"
"    background-color: rgba(255,150,15,200);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton#btn_buscar_estudiante:hover {\n"
"    background-color: rgba(255,209,15,200);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton#btn_buscar_estudiante:pressed {\n"
"    background-color: rgba(139, 69, 19,255);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}")
        self.btn_buscar_estudiante.setObjectName("btn_buscar_estudiante")
        self.lay_frm_datos.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btn_buscar_estudiante)
        self.lbl_nombre = QtWidgets.QLabel(Buscar_estudiante)
        self.lbl_nombre.setStyleSheet("font: 11pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.lay_frm_datos.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre)
        self.txt_nombre = QtWidgets.QLineEdit(Buscar_estudiante)
        self.txt_nombre.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom: 5px;")
        self.txt_nombre.setReadOnly(True)
        self.txt_nombre.setObjectName("txt_nombre")
        self.lay_frm_datos.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_nombre)
        self.lbl_notas = QtWidgets.QLabel(Buscar_estudiante)
        self.lbl_notas.setStyleSheet("font: 11pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_notas.setObjectName("lbl_notas")
        self.lay_frm_datos.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_notas)
        self.txt_notas = QtWidgets.QLineEdit(Buscar_estudiante)
        self.txt_notas.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom: 5px;")
        self.txt_notas.setReadOnly(True)
        self.txt_notas.setObjectName("txt_notas")
        self.lay_frm_datos.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_notas)
        self.lbl_puesto = QtWidgets.QLabel(Buscar_estudiante)
        self.lbl_puesto.setStyleSheet("font: 11pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_puesto.setObjectName("lbl_puesto")
        self.lay_frm_datos.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_puesto)
        self.spb_puesto = QtWidgets.QSpinBox(Buscar_estudiante)
        self.spb_puesto.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom: 5px;")
        self.spb_puesto.setReadOnly(True)
        self.spb_puesto.setObjectName("spb_puesto")
        self.lay_frm_datos.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spb_puesto)
        self.lbl_promedio = QtWidgets.QLabel(Buscar_estudiante)
        self.lbl_promedio.setStyleSheet("font: 11pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_promedio.setObjectName("lbl_promedio")
        self.lay_frm_datos.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_promedio)
        self.spb_promedio = QtWidgets.QDoubleSpinBox(Buscar_estudiante)
        self.spb_promedio.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"color: rgba(0,0,0,255);\n"
"padding-bottom: 5px;")
        self.spb_promedio.setReadOnly(True)
        self.spb_promedio.setMaximum(5.0)
        self.spb_promedio.setObjectName("spb_promedio")
        self.lay_frm_datos.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spb_promedio)
        self.lbl_foto_text = QtWidgets.QLabel(Buscar_estudiante)
        self.lbl_foto_text.setStyleSheet("font: 11pt \"Gill Sans MT\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_foto_text.setObjectName("lbl_foto_text")
        self.lay_frm_datos.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_foto_text)
        self.lbl_foto = QtWidgets.QLabel(Buscar_estudiante)
        self.lbl_foto.setMinimumSize(QtCore.QSize(178, 180))
        self.lbl_foto.setMaximumSize(QtCore.QSize(178, 180))
        self.lbl_foto.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border: 2px solid ;\n"
"\n"
"padding-top: 3px;")
        self.lbl_foto.setText("")
        self.lbl_foto.setPixmap(QtGui.QPixmap(":/images/persona.png"))
        self.lbl_foto.setScaledContents(True)
        self.lbl_foto.setObjectName("lbl_foto")
        self.lay_frm_datos.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lbl_foto)
        self.lay_ver_principal.addLayout(self.lay_frm_datos)
        self.gridLayout.addLayout(self.lay_ver_principal, 0, 0, 1, 1)

        self.retranslateUi(Buscar_estudiante)
        QtCore.QMetaObject.connectSlotsByName(Buscar_estudiante)

    def retranslateUi(self, Buscar_estudiante):
        _translate = QtCore.QCoreApplication.translate
        Buscar_estudiante.setWindowTitle(_translate("Buscar_estudiante", "Buscar estudiante"))
        self.lbl_buscar_estudiante.setText(_translate("Buscar_estudiante", "Buscar estudiante"))
        self.lbl_codigo.setText(_translate("Buscar_estudiante", "ID/Codigo: "))
        self.txt_codigo.setPlaceholderText(_translate("Buscar_estudiante", "Inserte ID/codigo"))
        self.btn_buscar_estudiante.setText(_translate("Buscar_estudiante", "Buscar"))
        self.lbl_nombre.setText(_translate("Buscar_estudiante", "Nombre: "))
        self.lbl_notas.setText(_translate("Buscar_estudiante", "Notas: "))
        self.lbl_puesto.setText(_translate("Buscar_estudiante", "Puesto: "))
        self.lbl_promedio.setText(_translate("Buscar_estudiante", "Promedio:"))
        self.lbl_foto_text.setText(_translate("Buscar_estudiante", "Foto: "))
from notas_estudiantes.images import imagenes_rc
